# NOTICE: Generated By HttpRunner. DO NOT EDIT!




def cloro_count(n, a):
    if n > 3:
        a += n // 3
        n = n // 3 + n % 3

        cloro_count(n, a)
    print(a)




cloro_count(100, 0)
