# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/all_fields_submit.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAllFieldsSubmit(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("打开表单")
            .get("https://mo.jinshuju.net/f/kQnsXG")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "if-none-match": 'W/"5c5832bdf457ad96c4a7d5f44d369e66"',
                }
            )
            .with_cookies(
                **{
                    "entry_token": "MNjpdEd2",
                    "gd_ssf": "MTYwMzMzMzkyMQ%3D%3D--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "start_filling_time_kQnsXG": "1603337174",
                    "csrf_token": "/4FakpisSoMQCGZP+Ee6NOmD1gZU4gt6H4zJj+1gTPKLOmpa4xbt/1QjCe06wTxG7dCENioL8xGj6tpGemRvpA==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337175",
                    "_gat_gtag_UA_48208031_13": "1",
                    "_gd_session": "K05OejljNWp4emI3b3NSVFo3aUxJM2JRckVibk84cGRINy9JcVh4dnkyZG1pUEZZaXh0aDExcXU2bnVVMlRqVHNqLzRzTDlYQkZnTDNIT1FJMDRUdmVjNy9Ta1BCNHBGTjJTSkUvSkRQbjJZd3Q0NVlmS1RaUlBYMTdLUEgvMUMxN21ITURnc1M3VDR6SFpNK3NiSjNZUVJJb3RQd21QaHRRK1VoeGgrN29lb01mbUlFZ3pBNURDL0RBc2JTWjVQOE4zZTl0QS9uZDdLc0lXOUpvQXFydkp3MmdyNCswcmZvbkVyVUlBWDk2OW9TM0xLZE8vUWdhSCtMR1d5QzZBVmhXYzFtM1h6QzlTamVqTUNBU3JQRVpSNDUyQ1VSbVYyRnBvRllDSXVhSVNMc1BoOHRJcmN0WThYQmdwU1BwMDUwSmRocTQyYVpZa05vdldvczY3VkxRPT0tLUFBOXFqYTlaWUtadStvelZGV21wclE9PQ%3D%3D--65551d83d112b6ed52ba0e075afdb36d5fe04911",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("ShowFeature接口")
            .post("https://mo.jinshuju.net/graphql")
            .with_headers(
                **{
                    "content-length": "204",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "_gd_session": "UzlqV2piS0J2LzJDMTFzbUhVbmJmSUJIczVEa1FkdzZsb2RnWW5BRE5iYStESlNoTkdFcUVMSzdTY0pOQ0pNL0dPa25HbjQ2ZkNOQmYwMVBGYmJqNVhreEJjb2hXbjA2OHhzODF3dDJoYVczVXVDQS9EM25sc0VhckNtRWlxVkNXdEZzR25iQlNoSS9NeTFBSlN0V3lsRU1PNkRvYllJT0plYjlYZ1NHRmVFR1Qrd1ZpMVdhODBGSUI1aldwbzlNaWVTWlYrWVBCb3JpeElrVVJpZXlRY0xaVnpOOWR6bXpnUDZOaUIyQlFJcHdUQnJJMmtVY2FEcnpVVXpLWW5SblZTTmNSQXJiTldjUG12NlRCSER5UnBVU253Y3pMZmIrVUZBazc4WkFkT0pPVGcwVEJ3U3dDRGlLZ1BBVWZnK3pZVFdYNEtQSWhhbkNzT2FLcXNFRTd3PT0tLVRKNUJPWXlpTmpwN0NPNGdoMy9XUlE9PQ%3D%3D--ecf52e23a6386e767a968b6bd1bdb8b34197e796",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                }
            )
            .with_json(
                {
                    "operationName": "ShowFeature",
                    "variables": {"key": "should_use_mobile_view"},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "69bac8320cb0db576c6d775ff9cda9c9de3ffbfdab3a8010e57eda56ef10e73d",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取publishedDynamicAttrs")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "211",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "Q3R5Q0ZxcEZCNTdWb25rZnAwb1hwZityWWFjVFRtWElpbS9wREZQVU1GcGkvRGlwa3hFejJmdkkwS2p6R3Zqc3ExZ1g4bHlsMFZ1MDExYWx4S1pCeWRDZ2gwQ2tONzlKeHVvRklpTE9MMmFLZy9DMDNieEFybnV1K1lZbFRKOStsZGZqYTFUZlJjQ0FETk5RK2ZhMndyRTBpWmNGeWFsak9LekFNTXlxS2taalNjb25JMlk1MEdQUmNwZVh5NWN4K2FGVHV4bUF6Y0FMejZ5dHdxaVJSQnpjaW5aUGMxQmhKNk5McUNiZWd6WU1JL0ZnQXVUUDNrTUZLU3lOMGkrTlhpWmp3TFk1UkFZcWYycklLL25GWFh2OWdQZ0NuODc2V3hnanViOGxtZDRKdGVrc0Y1eUZtNCtlUHdCVkYxQmYwT1I5emRpSHNiemxlbERMWStSMHBnPT0tLUQ4ckRlaWo4R3hOYmNhMDZ4Um8wRlE9PQ%3D%3D--7b162261b761b7d4a7d34cd7af16d24c29c9099b",
                }
            )
            .with_json(
                {
                    "operationName": "publishedDynamicAttrs",
                    "variables": {"formId": "kQnsXG", "code": ""},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "b9e02c3e968435ec4a86b4ff7ff00d4f89ccb593df0d24aa4b71735e1c9f822d",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("createEntryAttachmentPresignedToken")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "265",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "WXBMaWZKVXVSV1hGSjNBRUVjWXJnbXhzb3lpM2E2YlFSZEhKOVBEdjdSS3RCaGZndEJBM3lRQk1MQ0s0WXpHRkhjN3VYVUgwaEdrUVk5WUhGRzZtSEZOc0h6aEFWbTV4TCtPa2RSU2RUVFN4ZFNkSlNQczVzd2RYT1pGQTZtaUVZbHh6RUtpaitHcHYwQ250R0F3RExUOWczWi9nQWkzM2VseGluTjc0R1FKT2hzS0JqTDc3d1Q4NUFMZUtCZ3F2Vm5EaUZ0NVpYeXVOcmNvbGJOeDQ2NkhsbHR6RnpjQ3FUbnFDYzkySWQvTThQam5XaGY0SVFVZ0kzMHZ2ZnJwb214Nk9EMDl4QVBjanNFYXN0QUgveXN6VERkY1FRZ0x2MDFyTy81T3pNeStCeUlBRmg2Mit5NnhxY2tUNFF5eGNacWpDb0ZyTFdLbDZqdmJWOENFcnVRPT0tLUZIaHppQ0UwMmswSG1JV1ZreUVGVmc9PQ%3D%3D--a8913cf4a48ded55223212947ad1522000421255",
                }
            )
            .with_json(
                {
                    "operationName": "createEntryAttachmentPresignedToken",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "fieldApiCode": "field_11",
                            "prefix": "en",
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "813e069abde071fd7de77753062cb5a72e3e6309a436028b2e84f7065ad258e1",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("createEntryAttachment")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "735",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "RG56QktvWHBoRmR1WXFIRk9GeE45a0N1QjVsbFhtYWpuYlI4VmpuRWxMSHJXUVFPSDFnUDlqUnNqRmtuekFUbEpVbjAzM2o4d3pCRFNCNnJJY0VvWTJxY2UyUVF4bTdVZFQ0YUxOK2Zhbkg1LzExakJtRU9NL1huSjI4cDhINnZWclgzN3d2RmY5OU1GTXloWWRMK0haTFlPRTljc1EzWHV3SGE1bzFxWjVaN3ZiakUwZ2V2V2N4SVY3ZmJlT282RTNIMkJseE1GQjhQeXVlZWNLdUw2MlpOaVNqcnlRcEtMRTdUYTB2UjNhd3pzek1UZDZQbGIyem5udFJ5TjVCcDZleHU2Qmo2UWIrZjhjMDBmY2tVVFNndjAzWTJSSG9lVVEyeDBOU3RkVis2QzNKall2U2c0UkJ3Rk9RVUUvSmx1RFRmQmtDckJSc2N2R2oyaENVQU1BPT0tLU1SbFFYUFdPUnpOaFZLRGZ3VFdJZ2c9PQ%3D%3D--ef111971b6f905dad0dbf1c46b08a530dc8021ae",
                }
            )
            .with_json(
                {
                    "operationName": "createEntryAttachment",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "fieldApiCode": "field_11",
                            "prefix": "en",
                            "attributes": {
                                "securityCode": "LS0tCi0ga1Fuc1hHCi0gIXJ1Ynkvb2JqZWN0OkFjdGl2ZVN1cHBvcnQ6OlRpbWVXaXRoWm9uZQogIHV0YzogMjAyMC0xMC0yMiAwMzoyNjo0Ni43MTYzNjIxMzIgWgogIHpvbmU6ICFydWJ5L29iamVjdDpBY3RpdmVTdXBwb3J0OjpUaW1lWm9uZQogICAgbmFtZTogQXNpYS9TaGFuZ2hhaQogIHRpbWU6IDIwMjAtMTAtMjIgMTE6MjY6NDYuNzE2MzYyMTMyIFoK--b2b7e480c5c58ce3fef6f999f355b600",
                                "contentType": "image/jpeg",
                                "fileName": "ia_100000015.jpg",
                                "fileSize": 20407,
                                "key": "en/kQnsXG/FjaJAGY7XihuegJy3LNAcFDUgk0i_field_11_1603337206.jpg",
                            },
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "6f7ddd223dddfa96109ab99278c5a77280f0c675d64752e538d6edd39100682c",
                        }
                    },
                }
            )
            .extract()
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("RequestLocation")
            .post("https://mo.jinshuju.net/graphql")
            .with_headers(
                **{
                    "content-length": "178",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "aVAyZ0x3RlFtaWR4VENTWUE3L3ByZWEvUWovL29MTjVkeExBb1I3TE51Q3FGcFU0UDRvbUtDSjJBbjAvcG1zZ2V3d3ZvVm9SakRpQ1BvRSszYmpGZEtoWWdONThBbFJQY2RnSThhWnkyTFF2QXVCRVZWMk1pN2FNalNZcWJCekVmbEZpdURRS2NCTXRNZHB2ajE1VE0rN2t5SWl0c2NNQWRNSmRIVmRYSFNuK2NWZkFJeGszWEdZYkxrcFdDY3M4dm1LK2hjODZQZXNUR2kvc1lRSWVWejdjNFFKdWtiNFlMVGFwNFpyQjRiTGJGbGkvU0FGV2V6WHcrYkQwSTJneFArTHBqSHhCQWdtSEVqejFMeWNpT3BMNjZOUGNhWHRLQzk1K3dHNUFsUC9jeVZZVU5OMUE2MDBwNlFyak1zNVVma0xXakxHUCtNaVhoZndlNHBNdWRRPT0tLWFlRnhzbW0yY2dSTWcwNXpYZ05CdFE9PQ%3D%3D--ac852ec9bfcd481c14c8f06b0d79320a2764824f",
                }
            )
            .with_json(
                {
                    "operationName": "RequestLocation",
                    "variables": {},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "c1fb278d83828021dc3cf6010de1ee2e92e7eafccbe1b2cdd33c8cf954e67538",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("ValidatePublishedFormFields")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "818",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "NkNyL0dHOXlDR0pRSnJCMm9SKzBPVkF4TXpKbFNuaUtMalNKSnFoeTRINmdib0hHM0pFb1owMDdWdE9nZDI2TGhybVdYczIrYkYza3RNYUxkWDQzejJkQTlOazBSdDEwaTBOeDVrdEhxbm9ZNlQ0eDVmcFlhTnRxODlJTWdyelplbGxDbERXWHRTNGdPQ0FiSEE3RWcyZmhHaWZweitzU1dIVnNqbDZtNHFUZmtxclRNVm9GWjJTOXBFK2lZeEs3MmNYeURSM055YXNRMktHUkJVTGNUemEzRDlBUjN3THlKZzZ6U0ZTYXFFNGdqZkU0YmNjNHY2YUNobGRyakpzK0RHdDhTa1pJbWJBQmFVaEZWeG11OWRDemtlNUdHWGUyRW5MNTBqSHlqOWVtUW95ejRZdTVUaGNreWFyd3VlY2xCTHB0QzV4eVdxeTM4NkhhZXZiekZ3PT0tLTIvRnR2VmJvTUpNNkwzdlJmRzhLZ0E9PQ%3D%3D--5c4a752a779956a674519d870d904b09b498d441",
                }
            )
            .with_json(
                {
                    "operationName": "ValidatePublishedFormFields",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "entryAttributes": {
                                "field_2": "这是全字段表单",
                                "field_3": "这是全字段表单1\n这是全字段表单2\n这是全字段表单3",
                                "field_4": "mpkW",
                                "field_5": ["jSCe", "KMDl"],
                                "field_6": "5q43",
                                "field_7": ["barw", "ji40"],
                                "field_8": "XHkB",
                                "field_9": {"level_1": "pdtu", "level_2": "sErU"},
                                "field_10": "123",
                                "field_11": ["5f90fbf75b65166d7c107df2"],
                                "field_12": {"hour": 11, "minute": 26},
                                "field_13": "2020-10-22",
                                "field_14": "https://jinshuju.net",
                                "field_15": {
                                    "latitude": 22.316554,
                                    "longitude": 114.174328,
                                    "address": "香港特别行政区油尖旺区亚皆老街旺角汇丰银行大厦",
                                },
                            },
                            "xFieldWeixinOpenid": None,
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "75a54531d39e80dab8254c4674b22bda0aee525952d1015298be17370601bf3c",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("AddressData")
            .post("https://mo.jinshuju.net/graphql")
            .with_headers(
                **{
                    "content-length": "190",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "VkdNZDFhdUFQQXUvZ0FERStiMTZoaXlTQmtYZkFwQkFyZzZUZFd5MmlvcTB3ZUlTdnB4b2Q3TWEyTjZrMkNrK1BnQkdnWlpFSHp6TTVQOUZLWVhNZ3lCeS94SE1kOGlSTWRmUFY2bDhtdnlEVzcwUzdYMWRuK0dPQ1E3azJVN2pFb21QeVQ2REljL0pjYWl2THhlVzFCcTlQcGdaSlduL2dkeitKZHlvYTdRYzlkRm0wZ3oySnNxZSttUElTbmpocS8ybGNjbHN2R0p2UFF4aWE1dStUN1JwNFo5eVh2UC9EV1FJTlU3ZTZ2ZHNRalVjYVd1NDM1U0NoK2MwRlQrd0gzQThPdTZrTjhPckV6UWhmMEMzcktBQWxTbTFSQnBCbzhlWHNNTDExTS9FVER6SVZ1RlhvaWcvOEpBZlJ1dHQ4TUxoYlhyYWZpbkZkdHYydmJ5NnpnPT0tLXkwU253bjExQTZOcVV3SGhwVmNBc0E9PQ%3D%3D--734b8905b07f04979fad688164d8a66e19aca0f5",
                }
            )
            .with_json(
                {
                    "operationName": "AddressData",
                    "variables": {"locale": "zh-CN"},
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "538df51fee749e696ad089428cb67e1f6630dfc49e0b4c54099188db91b45abb",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("CreateCalculation")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "276",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "VkdNZDFhdUFQQXUvZ0FERStiMTZoaXlTQmtYZkFwQkFyZzZUZFd5MmlvcTB3ZUlTdnB4b2Q3TWEyTjZrMkNrK1BnQkdnWlpFSHp6TTVQOUZLWVhNZ3lCeS94SE1kOGlSTWRmUFY2bDhtdnlEVzcwUzdYMWRuK0dPQ1E3azJVN2pFb21QeVQ2REljL0pjYWl2THhlVzFCcTlQcGdaSlduL2dkeitKZHlvYTdRYzlkRm0wZ3oySnNxZSttUElTbmpocS8ybGNjbHN2R0p2UFF4aWE1dStUN1JwNFo5eVh2UC9EV1FJTlU3ZTZ2ZHNRalVjYVd1NDM1U0NoK2MwRlQrd0gzQThPdTZrTjhPckV6UWhmMEMzcktBQWxTbTFSQnBCbzhlWHNNTDExTS9FVER6SVZ1RlhvaWcvOEpBZlJ1dHQ4TUxoYlhyYWZpbkZkdHYydmJ5NnpnPT0tLXkwU253bjExQTZOcVV3SGhwVmNBc0E9PQ%3D%3D--734b8905b07f04979fad688164d8a66e19aca0f5",
                }
            )
            .with_json(
                {
                    "operationName": "CreateCalculation",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "attributes": {
                                "targets": ["field_32"],
                                "variables": {"field_10": "123"},
                            },
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "610f1b83d8930f26e829368560fe65c5773aa1907c161ec2bba9ff78aa9cc217",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("CreateCalculation")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "328",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "VHRPanFtSldZOHZYenRYOVNsRmNlZUpGcWFYejFqYlVQL3pPVXdMNEhyV0NmM1NYYVFONGEzZEJXVnZhVXRGZlVnK2NocmgrV1dIMkxPMzdMdERVRERRcFNVNHNUMVhTaHRrZVJMSzhVeXlRb1J3QnRQKzNIaEZvRVFZME10T3dUQVV4WDhlelcvR1JhL05HSFRvd1NIeUpnbm1WQmJSaWc2YVVhQk4rdXpPWGhzZHIrRE1JeHBGYzFIODdQSWxYUzBxb1RJSEJrNGJvRkw3TXl1b3Y4bUlkNXJabTNlNDFLeVlQay8wWk9iVjcxSS9sNzJyYkRmQ2VkWjhKOU5UTlBnQXk0THhVMVdHY2hNeGlFaXExTmUyOUdmUkFmLzZPZURvZHBkbGJHUGJjdlp1YW90ZjFLdmFCWE5STXMyKzJpRUh1V2ZQRnJaUDk3Znh6a01JVWRnPT0tLWFnSmxyL3dIV3pOUFJNQVh2anNqNEE9PQ%3D%3D--05d3304a14fb8dd851694d50384352448d0a2d9b",
                }
            )
            .with_json(
                {
                    "operationName": "CreateCalculation",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "attributes": {
                                "tabularApiCode": "field_24",
                                "statementApiCode": "vuIk",
                                "targets": ["field_7"],
                                "variables": {"field_6": "123"},
                            },
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "610f1b83d8930f26e829368560fe65c5773aa1907c161ec2bba9ff78aa9cc217",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("publishedAssociatedEntriesOptions")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "292",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "YXZ0SllTWFZoNGNtVWFqUk56NGJhRXdPYzJOcXFTZVRQcmZZTStMZmE2eE1nWFJWRWVncCtVTlQ5VEd3MWlyQm5OVTErUXU0c292aWRCaEd4QUxTTGhUTkRMRnlFSWhTUTc2YUQ1YWx0R1RMQzlFRmhIeGR1eUwyTVUwL1FUanl0ZlUxdTNLcUg0eTlhaS9pV2tYSTM1bnpDSGgvdGlONVVoTXZ2My9tNktseUR2SXFGS1V1T2hxZE9TdERjOUZ4VjZIZ0NsTmtaa0JuRFRCbVQySFcvQkluWVRYNnc4Sis4UWdJcjNMT1NtUms1QnRxYmRBd2c5R29DZnFFWGF4dE1qNCtHVFQyN3FSZEpOczhqVkxEUm80Rzl4UUZveWZUNi8rTlVCS2FVM3MySnlpMjB2YVh3QjM4RVErSDNXWkVDY203T0xUZDFzdm5Ta3l5UWFhQVZRPT0tLWh3VlowU1AyYk8xdDh6dzVHS0pPdXc9PQ%3D%3D--06c78f89d3f9f74011c101d6c6349765bf6825ce",
                }
            )
            .with_json(
                {
                    "operationName": "publishedAssociatedEntriesOptions",
                    "variables": {
                        "formId": "kQnsXG",
                        "fieldApiCode": "field_27",
                        "associatedFieldApiCode": "field_1",
                        "first": 20,
                        "q": "",
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "9849dd2672115f7611605f78e996030754d9cc5d40d19f94c6f68ffc1f2ebbb2",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        # Step(
        #     RunRequest("CreateESignatureAttachment")
        #     .post("https://mo.jinshuju.net/graphql")
        #     .with_headers(
        #         **{
        #             "content-length": "44995",
        #             "accept": "*/*",
        #             "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
        #             "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
        #             "x-entry-token": "MNjpdEd2",
        #             "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
        #             "content-type": "application/json",
        #             "origin": "https://mo.jinshuju.net",
        #             "sec-fetch-site": "same-origin",
        #             "sec-fetch-mode": "cors",
        #             "sec-fetch-dest": "empty",
        #             "referer": "https://mo.jinshuju.net/f/kQnsXG",
        #             "accept-encoding": "gzip, deflate, br",
        #             "accept-language": "zh-CN,zh;q=0.9",
        #         }
        #     )
        #     .with_cookies(
        #         **{
        #             "_ga": "GA1.2.656726061.1598346722",
        #             "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
        #             "country_code": "CN",
        #             "filled_form_scene": "form",
        #             "clone_form_lrhGWN": "true",
        #             "clone_form_Jxy5a4": "true",
        #             "jsj_locale": "zh-CN",
        #             "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
        #             "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
        #             "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
        #             "mixpanel_event_history": "open_publish_link",
        #             "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
        #             "_gid": "GA1.2.1488595163.1603333419",
        #             "last_fill_entry_token": "MNjpdEd2",
        #             "start_filling_time_kQnsXG": "1603337184",
        #             "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
        #             "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
        #             "_gd_session": "LzRaVExDdHpFRlRpKzQ2WG5mMDYyTEhaMzhxd0k2MHZwNkF2OTJxUXhZcU5Nc25weGdpWXpLblExSGUzUXAwRFBFc2w2RXpCdVlyN3p5KytTNUdMaE5kWTd0M3FDajB5R05lZjJRSms0S3BrR0tNZGpBUUF0NldyOWNKWHdlbzMwTFhBSFJJbitOMzBGeURIc2llamR3bDFmdVNVdFEwNVNCOW1HeDRsZGVMdDBWK1Z1LzYrcEluZFVhTFUzQlMyZU5jL2JnNkVFbE5lQnNodkNSQzhaNUl5UlhyWlVZRWtOZmdaM0tlVm1PemFXSEFwLzdja0IxbUY4eFF5aTcyNkp6ZzROTmhTWlg0cjdwS1UvUkxpcEIyMXpoa3ZBcU5MMGNmSlo2UmpHelZmeDBUaGVtdTNKSHN2TnBsSWlLcXh3bU8wM2UzMkQxUlBLRVhQZSt4eGNBPT0tLWNVeElwOG5zMVpjSUQ4TXdyYjZQRUE9PQ%3D%3D--4e139f1a0f2bbd94fb5957dfbad5812092cfe8ac",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "operationName": "CreateESignatureAttachment",
        #             "variables": {
        #                 "input": {
        #                     "formId": "kQnsXG",
        #                     "fieldApiCode": "field_31",
        #                     "prefix": "ens",
        #                     "dataUri": "${get_bs64_image()}",
        #                 },
        #             },
        #             "query": 'mutation CreateESignatureAttachment($input: CreateEntryAttachmentInput!) {\n  createEntryAttachment(input: $input) {\n    attachment {\n      id\n      largeUrl: visitUrl(size: "large")\n      __typename\n    }\n    errors {\n      message\n      code\n      path\n      __typename\n    }\n    __typename\n  }\n}\n',
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        # ),
        Step(
            RunRequest("CreatePublishedFormEntry")
            .post("https://mo.jinshuju.net/graphql/f/kQnsXG")
            .with_headers(
                **{
                    "content-length": "1832",
                    "accept": "*/*",
                    "x-gd-ssf": "MTYwMzMzMzkyMQ==--99975c30047628c34c6d3aebdf0cdcacde9762d3",
                    "x-csrf-token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "x-entry-token": "MNjpdEd2",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "last_fill_entry_token": "MNjpdEd2",
                    "start_filling_time_kQnsXG": "1603337184",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "_gd_session": "VVNNS1NBYS9XbVdZajdXbXVhanVXek5SUUFOeFgrMDR5Y1ZZTnRRckUxUkNyTkRqejVQWDZHcXVQUmRmeEYrNUIvTnBXa1lnbUNRd2kwNlVjSE51ZTdMRjBSQS9yUGt2SitDMjBOY2MvUU95bXUzaDRHVVYvWVVzUkFVdmNod04wSDVNMlBUSzUySlgvYU0wSW1pMWV0WUJHa05nWHo5OVVMc3dWNU91aWRTRHNqN0UxSmlqZm05SkVJQXU4YmtwWEZubi9DNGFtcUJHS0xXNXVJSjNFKzduSFM3VXVsV1BUem9KbXkvTUFRYWdWOTRoR1VrbnRmaTdMRTVzOTVvWGUvY0hXTVFlTm9vSUVzR3VYUDhER3Z6TGNwYXFzSU03bHJlZ1dxbjE1NGpzM3pSeHlIamNjQkxwRmozdUNyYURaZnd2Y25aR0s0clVDZ2lra2VEMlZBPT0tLVdzSlJwOUVjS2JPa3ZKb3MxTGgzNkE9PQ%3D%3D--cf37712c5bc99a7b66e1c676f5490b0c83c3d8e8",
                }
            )
            .with_json(
                {
                    "operationName": "CreatePublishedFormEntry",
                    "variables": {
                        "input": {
                            "formId": "kQnsXG",
                            "entryAttributes": {
                                "field_2": "这是全字段表单",
                                "field_3": "这是全字段表单1\n这是全字段表单2\n这是全字段表单3",
                                "field_5": ["jSCe", "KMDl"],
                                "field_7": ["barw", "ji40"],
                                "field_9": {"level_1": "pdtu", "level_2": "sErU"},
                                "field_10": "123",
                                "field_12": {"hour": 11, "minute": 26},
                                "field_13": "2020-10-22",
                                "field_14": "https://jinshuju.net",
                                "field_15": {
                                    "latitude": 22.316554,
                                    "longitude": 114.174328,
                                    "address": "香港特别行政区油尖旺区亚皆老街旺角汇丰银行大厦",
                                },
                                "field_19": "张三",
                                "field_20": "18383157715",
                                "field_22": "020-12314",
                                "field_23": {
                                    "province": "山西省",
                                    "city": "大同市",
                                    "district": "云州区",
                                    "street": "测试",
                                },
                                "field_24": {
                                    "vuIk": {
                                        "field_1": "撒发大水发",
                                        "field_2": "爽肤水",
                                        "field_4": "2020-10-22",
                                        "field_6": "123",
                                        "field_3": {
                                            "level_1": "n0dp",
                                            "level_2": "Ijtg",
                                        },
                                        "field_7": 15129,
                                    },
                                    "-19j": {
                                        "field_1": None,
                                        "field_2": None,
                                        "field_4": None,
                                        "field_6": None,
                                        "field_3": {},
                                    },
                                    "B6d3": {
                                        "field_1": None,
                                        "field_2": None,
                                        "field_4": None,
                                        "field_6": None,
                                        "field_3": {},
                                    },
                                },
                                "field_25": {
                                    "KnDC": "DTIV",
                                    "RYAj": "eCRk",
                                    "Zgx5": "sc7W",
                                },
                                "field_26": [
                                    {
                                        "field_1": "第三方的",
                                        "field_2": "奥术大师多",
                                        "field_3": "2020-10-22",
                                    }
                                ],
                                "field_27": "5dd62b9e66ab337b25b32189",
                                "field_4": "mpkW",
                                "field_6": "5q43",
                                "field_8": "XHkB",
                                "field_11": ["5f90fbf75b65166d7c107df2"],
                                "field_32": 15129,
                                "field_21": "vvtianll@163.com",
                                "field_28": 5,
                                "field_29": 5,
                                "field_30": ["TEzV", "KS7h", "01yJ"],
                                "field_31": "5f90fc565b65166d80107d57",
                            },
                            "captchaData": None,
                            "weixinAccessToken": None,
                            "xFieldWeixinOpenid": None,
                            "weixinInfo": None,
                            "prefilledParams": "",
                            "embedded": False,
                            "backgroundImage": False,
                            "formMargin": False,
                            "hasPreferential": False,
                            "fillingDuration": 120,
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "4cd6a9aef2820b2c3215f6ddfa87093869461f76f3f2016738f4307268a7df98",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("success")
            .get("https://mo.jinshuju.net/f/kQnsXG/success")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mo.jinshuju.net/f/kQnsXG",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "if-none-match": 'W/"66a90001c25d0a5662eb3c9e87e9f000"',
                }
            )
            .with_cookies(
                **{
                    "entry_token": "yavelHD9",
                    "gd_ssf": "MTYwMzMzNzMwNg%3D%3D--6aebb394cea4bd376b145abee66cc45233d58378",
                    "formSubmitSuccess": "1",
                    "_ga": "GA1.2.656726061.1598346722",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "filled_form_scene": "form",
                    "clone_form_lrhGWN": "true",
                    "clone_form_Jxy5a4": "true",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_mo": "IjVmNzFhOWU0NWI2NTE2NjNhN2FhMDkxNSI%3D--a14f10994021cef461ef098be5744ff9e6e00e51",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "mixpanel_event_history": "open_publish_link",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1601280110,1603333419",
                    "_gid": "GA1.2.1488595163.1603333419",
                    "csrf_token": "ANIfc/NL0riig7hLr6Grvpp+yxDlSi531mbPAeOsYb50aS+7iPF1xOao1+ltJy3Mni2ZIJuj1hxqANzIdKhC6A==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603337185",
                    "last_fill_entry_token": "yavelHD9",
                    "_gd_session": "eHlzNjExd2hRUGZnaTdWdVp5R0VOUVRqOWtoVFMrUzVrd1FKYVBrdG52OVBMVUJPUWlwWlMyWXNLcDdrTTRlcjh6STBiWjdTQW9KNkxmbkFKdjMwNi94UG9PbTFwaVkvelBPelJRL2JtNXVXeXU0YnBtYjl5aHd0UkF6L2x1Q3J3YWU3SXpWV2xwOGVZSTg5a3JNWXpXSHFUVmwyeHVvL1phblQrTk1XbEFEdmtBVGxDLzJJTTBkcTRMMWI1M3F0MHpxZkM5djJ1MlFValFMK3ZSaWtkTyt1K0h0RnpGV21BNWFrdm5lOEt3UkxWZTN1TGN1cWhiQXliekwxTld1ZnUyNURUL2VSZ3RBMy9zNlVaN2czYVp1U2VRcDI0RXE1eFluKzJNdnZ6TW5uaFJhNVRyYWhNRUZSQ0VlcUFuWUFUNlppVE53d1MwbXB3dzFlVk16eFhRPT0tLW5Jb2RTUTVnK3ordlYxS0s5bzZTdFE9PQ%3D%3D--24460e2f9b9c67a1ef5e2959933e03946c50164c",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseAllFieldsSubmit().test_start()
