# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/get-candlestick.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetCandlestick(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${ENV(UAT_BASE_URL)")
     @pytest.mark.parametrize("param", Parameters(  

        {"desc": ["${read_yaml()}"[0]}  

    ))  

    def test_start(self, param):  

        super().test_start(param)  

    teststeps = [
        Step(
            RunRequest("/v2/public/get-candlestick")
            .get("v2/public/get-candlestick")
            .with_params(**{"instrument_name": "BTC_USDT", "timeframe": "5m"})
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(**{"__cfduid": "dcb695eb677c5a40e841705ef79415c651617014441"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetCandlestick().test_start()
