# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu_create_doc.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuCreateDoc(HttpRunner):

    config = (
        Config("testcase description")
        .verify(False)
        .base_url("https://mubu.com")
        .variables(
            **{"host": "mubu.com", "phone": "18383157715", "password": "749511.Tll@"}
        )
    )

    teststeps = [
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "reg_prepareId": "174fe320e49-174fe320e07-4b2c-bdac-e6a4c6f6dee1",
                    "reg_focusId": "f9890663-7008-4b2c-bdac-174fe3210c7",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "SLARDAR_WEB_ID": "0927d80e-cefd-4f9a-8d94-b3e101f16b52",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992738",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "SLARDAR_WEB_ID": "f3cb791c-2877-4d8e-916b-581b087e473e",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992745",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("/api/login/submit")
            .with_headers(
                **{
                    "content-length": "54",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992746",
                    "SLARDAR_WEB_ID": "17596d70-19bd-4759-877e-276124cc85cd",
                }
            )
            .with_data({"phone": "$phone", "password": "$password", "remember": "true"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.next", "/list")
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992746",
                    "SLARDAR_WEB_ID": "17596d70-19bd-4759-877e-276124cc85cd",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992746",
                    "SLARDAR_WEB_ID": "17596d70-19bd-4759-877e-276124cc85cd",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992746",
                    "SLARDAR_WEB_ID": "17596d70-19bd-4759-877e-276124cc85cd",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.folderId", "0")
            .assert_length_greater_than("body.data.folders", 1)
            .assert_equal("body.data.folders[0].name", "在线收款测试设计")

        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992746",
                    "SLARDAR_WEB_ID": "17596d70-19bd-4759-877e-276124cc85cd",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/create_doc")
            .post("/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "17",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                    "SLARDAR_WEB_ID": "7b9b9ce5-76d0-4d0e-9bb0-e339df52d886",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992753",
                }
            )
            .with_data({"folderId": "0", "type": "0"})
            .extract()
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/doc$docId")
            .get("/doc$docId")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "729aece6-2548-4e43-b941-785e0037bb34",
                    "csrf_token": "9b6090ce-e102-4c4b-9d7c-b944959d3934",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "_ga": "GA1.2.50872514.1601992526",
                    "_gid": "GA1.2.331049411.1601992526",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1601992526",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DKsMrxiFFSX87qre4S8aD7fxs1SWdKQHC5uiBA3gZQVS%26wd%3D%26eqid%3Dab0f69780001d31a000000065f7c774a",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "mubu_inner": "1",
                    "s_v_web_id": "kfy10rqd_xgAQeArA_QxHn_4ntu_A7Qq_csOIRLF7r2a2",
                    "_gat": "1",
                    "SESSION": "1a04a51b-9fd1-47ff-a7f3-31bdaca899cb",
                    "reg_prepareId": "174fe355e7e-174fe355e58-4e82-b429-96528a3a43c3",
                    "reg_focusId": "b3b191a1-0714-4e82-b429-174fe356250",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user_persistence": "f1031bb3-c69a-42db-a99c-727bf2d4a7ac",
                    "SLARDAR_WEB_ID": "7b9b9ce5-76d0-4d0e-9bb0-e339df52d886",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1601992753",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_user")
            .post("https://api2.${host}/v3/api/user/current_user")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "0e164a6e-7454-491c-ab8d-002c32722781",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/get")
            .post("https://api2.${host}/v3/api/document/get")
            .with_headers(
                **{
                    "content-length": "22",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "20b4ca80-56a9-4aa2-8113-0f4cc95c4b58",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.${host}/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "28",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "90794969-124d-4510-a548-074e060a6270",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.${host}/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "cd1f6454-e174-467e-8211-7751d8237f93",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.${host}/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "b9b4d90b-7172-4343-944b-6b2561629a93",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.${host}/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "049af447-4a6a-413b-9366-d33a350db5e0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "4494579429928814", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://${host}",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.${host}/v3/api/colla/members")
            .with_params(**{"memberId": "4494579429928814", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "request-id": "members:4494579429928814:1601992757915",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "x-request-id": "3c5f254f-4c10-4765-a515-c4104e0fdda7",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "403",
                    "member-id": "4494579429928814",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "request-id": "MESSAGE:4819515:4494579429928814:3",
                    "x-request-id": "0bff3284-f978-4a94-98c8-f90d958c6c19",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:4819515:4494579429928814:3",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "d", "original": ""},
                                {"name": "nameChanged", "title": "de", "original": "d"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.454",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.${host}/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "411",
                    "member-id": "4494579429928814",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "95c2b590-07db-11eb-aae3-6d0e70aab7da",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDgxOTUxNSIsImV4cCI6MTYwNDU4NDc1MiwiaWF0IjoxNjAxOTkyNzUyfQ.N-kNMHFqrI7GZbbhfkno1VJl-BGwmCDt2GHUeUnu5amJKL7zsxDJSGVRIXfcLCqEeSXbiTeuarfhMdn_U3kN_w",
                    "request-id": "MESSAGE:4819515:4494579429928814:5",
                    "x-request-id": "3997b337-31a0-4946-ad2a-fcee72872215",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/doc$docId",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:4819515:4494579429928814:5",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 1,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "dem",
                                    "original": "de",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "demo",
                                    "original": "dem",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "10.15.6",
                        "appVersion": "1.0.0.454",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreateDoc().test_start()
