# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mul_field.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMulField(HttpRunner):
    config = Config("testcase description").verify(False).export("a_response")

    teststeps = [
        Step(
            RunRequest("/f/jDRmyn")
            .get("${ENV(BASE_URL)}/f/OHgnwc")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "if-none-match": 'W/"2477d104de7bc5ea8dd45f2112e3065a"',
                }
            )
            .with_cookies(
                **{
                    "jsj_uid": "ad89599c-2a40-42d0-af2b-e092b36f051b",
                    "start_filling_time_jDRmyn": "1604311832",
                    "csrf_token": "WmbUm2AB50DyF0bWgqQjyC7daB6JRfMA1e83rtgWOhVOYQevb0ZSLqcbGCBFjTyeMyY/ChM4BmYGm/VxGId2Pw==",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1604311834",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1604311834",
                    "_gd_session": "azVoblFtR3ZlOGJta2wwWjhUd3NPdTVvT3VyVkUrNE5waU5Qb25ZQmRLdVZqajBNSXR4dnZBS0dGa1VDS3Rna21CSlJMaVZQb3NuRWx0VGNhVWdPVWl6STE1VnNUL3BmTjg0Qm93b0V0cUxXd0Jyc0hYZ1RDckw3eWx5Y0tjUUUxSWE0SkpZbXYwS3VBU1JmakhmUGtnPT0tLTJVbnM3WFlYaERldm5FRWl1SkFqQWc9PQ%3D%3D--7574f0b0a322b96b5aba20556cf421766c71d417",
                    "filled_form_scene": "form",
                    "_ga": "GA1.2.374196750.1604311835",
                    "_gid": "GA1.2.1293992417.1604311835",
                    "_gat_gtag_UA_48208031_13": "1",
                }
            )
            .extract()
            .with_jmespath("body", "a_response")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/graphql/f/jDRmyn")
            .post("${ENV(BASE_URL)}/graphql/f/OHgnwc")
            .with_headers(
                **{
                    "content-length": "581",
                    "accept": "*/*",
                    "x-csrf-token": "/acWuMPVyrfFTQ2LBJ0rlFl7fiLrhypMcg7ztLrU4n/poMWMzJJ/2ZBBU33DtDTCRIApNnH63yqhejFrekWuVQ==",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "${ENV(BASE_URL)}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "${ENV(BASE_URL)}/f/jDRmyn",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "jsj_uid": "ad89599c-2a40-42d0-af2b-e092b36f051b",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1604311834",
                    "filled_form_scene": "form",
                    "_ga": "GA1.2.374196750.1604311835",
                    "_gid": "GA1.2.1293992417.1604311835",
                    "_gat_gtag_UA_48208031_13": "1",
                    "start_filling_time_jDRmyn": "1604311841",
                    "csrf_token": "/acWuMPVyrfFTQ2LBJ0rlFl7fiLrhypMcg7ztLrU4n/poMWMzJJ/2ZBBU33DtDTCRIApNnH63yqhejFrekWuVQ==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1604311843",
                    "_gd_session": "K1hwemk0K2VwenV1amM3WlF0RTJURFc4WE1GT25IUUlDTi8wWi9wck5pbWc1ZUp5aS8rTEcxM2c0a1pHckdkRUNlczdzLzJQZ3poUmtJbE13bjNwY0Z6eEthcmpJUGdqMDlwS245dFRKc3JxZTBmc1hiVUdaOTlhdmhjQmhmM1JrMUdBR0xVNWh3anY2RWI2enk5YnJ3PT0tLU5vZ1NtTjNPS3gvdXpNYjlRcUlsZXc9PQ%3D%3D--05e0603a72147806e1c1904b1631eaa6ffa8d50e",
                }
            )
            .with_json(
                {
                    "operationName": "CreatePublishedFormEntry",
                    "variables": {
                        "input": {
                            "formId": "OHgnwc",
                            "entryAttributes": "${get_field_codetype($a_response)}",
                            "captchaData": None,
                            "weixinAccessToken": None,
                            "xFieldWeixinOpenid": None,
                            "weixinInfo": None,
                            "prefilledParams": "",
                            "embedded": False,
                            "backgroundImage": False,
                            "formMargin": False,
                            "hasPreferential": False,
                            "fillingDuration": 17,
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "4cd6a9aef2820b2c3215f6ddfa87093869461f76f3f2016738f4307268a7df98",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/f/OHgnwc/success")
            .get("${ENV(BASE_URL)}/f/OHgnwc/success")
            .with_params(
                **{
                    "e_token": "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjpbIlNNM0s5d1MzIiwiNWY5ZmQwMjg1YjY1MTY0NTRjNzA3NDM3Il0sImV4cCI6MTYwNDM5ODI2MH0.vVHJ3Mz4rpVWNGouEBUTrPMjzZjvvjdUq8gcO4ekEaU"
                }
            )
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "${ENV(BASE_URL)}/f/jDRmyn",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "entry_token": "SM3K9wS3",
                    "gd_ssf": "MTYwNDMxMTg2MA%3D%3D--5b7fe6ee25c58737f7cb98d9d2a35cf2fb81f6c2",
                    "formSubmitSuccess": "1",
                    "jsj_uid": "ad89599c-2a40-42d0-af2b-e092b36f051b",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1604311834",
                    "filled_form_scene": "form",
                    "_ga": "GA1.2.374196750.1604311835",
                    "_gid": "GA1.2.1293992417.1604311835",
                    "_gat_gtag_UA_48208031_13": "1",
                    "csrf_token": "/acWuMPVyrfFTQ2LBJ0rlFl7fiLrhypMcg7ztLrU4n/poMWMzJJ/2ZBBU33DtDTCRIApNnH63yqhejFrekWuVQ==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1604311843",
                    "last_fill_entry_token": "SM3K9wS3",
                    "_gd_session": "MTlNdUNaeVFkc2hxWHpwSUY4R0ViWEc2VStYRFUxQUVldFRxVy9iZ0hFd3hZKzZNczN3NlJacVc5RjBSd3p3cEVoMDVjZ1VyWjQzRC9obTJQWHE3emVNUEhmTFBIWXpnUHhhWjZKKy9NYmZTSlVrRE1Sa0N1Vlp5V01YUEpvTGplcmJ6Qkx3TzdOMXVDWExKcE93eVhnPT0tLXJHVnZ2UjViZyswQXhYdWdHa09BZFE9PQ%3D%3D--d74fe72750ac48de8c630db0359b4342a6a36f3f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseMulField().test_start()
