# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/red_package.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRedPackage(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        # Step(
        #     RunRequest("调用wx接口")
        #     .get("https://jinshuju.net/f/oIR3qk")
        #     .with_headers(
        #         **{
        #             "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        #             "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
        #             "accept-language": "zh-cn",
        #             "accept-encoding": "gzip, deflate, br",
        #         }
        #     )
        #     .with_cookies(
        #         **{
        #             "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
        #             "_gd_session": "eGY3dWtXSmtDV0JpODdQMkZvOFl0UUJtejJubHZFMWpTYTRyVjRTbG82ejFvVVJPSkZ1bUpjNnI0KzcxZzRmZFNkN2RDbnl6SlMvdGRQbUFQNlRzVWp5WUhGbktvUDBzbERoY2xCWFpKVlpyNUNWSVdtdkVSL2J4Z3NSWUhZZ1QrdWNZN0NrQWRydmkwZ0c5RDJhUGpnPT0tLW1TVWIvcW16K2VQRHdQblNEckM4U0E9PQ%3D%3D--a4346c7c8eff4339d011ab2c3a833839fb8719d9",
        #             "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
        #             "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680029",
        #             "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
        #             "_ga": "GA1.2.1734022612.1602570241",
        #             "_gid": "GA1.2.1232973062.1603676817",
        #             "filled_form_scene": "form",
        #             "last_fill_entry_token": "rBXDceWv",
        #             "csrf_token": "m3JtZn2lLDHPiJz0p0wu4bx3enYulsmIMrwca0/TILmxRb7cUcr9WHtKeIvfdhuTYmaOm+3/ldmXTaHv/V2xjQ==",
        #             "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
        #             "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
        #             "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 302)
        # ),
        # Step(
        #     RunRequest("/weixin_oauth/callback")
        #     .get("https://wx.jinshuju.net/weixin_oauth/callback")
        #     .with_params(
        #         **{
        #             "form_id": "oIR3qk",
        #             "code": "071uY61w36kabV2HO34w3xIKiw1uY619",
        #             "state": "published_form_base",
        #         }
        #     )
        #     .with_headers(
        #         **{
        #             "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        #             "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
        #             "accept-language": "zh-cn",
        #             "accept-encoding": "gzip, deflate, br",
        #         }
        #     )
        #     .with_cookies(
        #         **{
        #             "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
        #             "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680029",
        #             "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
        #             "_ga": "GA1.2.1734022612.1602570241",
        #             "_gid": "GA1.2.1232973062.1603676817",
        #             "filled_form_scene": "form",
        #             "last_fill_entry_token": "rBXDceWv",
        #             "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
        #             "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
        #             "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
        #             "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 302)
        # ),
        Step(
            RunRequest("/f/oIR3qk")
            .get("https://jinshuju.net/f/oIR3qk")
            .with_params(**{"code": "071uY61w36kabV2HO34w3xIKiw1uY619"})
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "accept-language": "zh-cn",
                    "accept-encoding": "gzip, deflate, br",
                }
            )
            .with_cookies(
                **{
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "_gd_session": "TllDbzhaQ01oVUQ3b1NSMUFWY2gyb1AycUJaUWRrOGlJZU42dXBJWmcvVEd6RkR5V0ZYNW1TWTd6d24wRkZOSjVCSXlGTmgzMTVkNnpPcjhlaThSeU1sR294ZTF3aU5JTXQ3SUxnZ3RUa2srOXpmRU81dXZQYXZZSVpZTDIzY0pWVWdidnVlcEhQbGg2YjhzU0lSOFJBPT0tLXROZEdadUJtQUQ0bFJCejliVHlNNkE9PQ%3D%3D--5b936bc2078319fa1e403b48dd01b8dcf74304ea",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680029",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "filled_form_scene": "form",
                    "last_fill_entry_token": "rBXDceWv",
                    "csrf_token": "m3JtZn2lLDHPiJz0p0wu4bx3enYulsmIMrwca0/TILmxRb7cUcr9WHtKeIvfdhuTYmaOm+3/ldmXTaHv/V2xjQ==",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/graphql")
            .post("https://jinshuju.net/graphql")
            .with_headers(
                **{
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "*/*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-cn",
                    "origin": "https://jinshuju.net",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "referer": "https://jinshuju.net/f/oIR3qk?code=071uY61w36kabV2HO34w3xIKiw1uY619",
                    "content-length": "204",
                    "x-csrf-token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680170",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gat_gtag_UA_48208031_8": "1",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "csrf_token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "_gd_session": "Y3lrYytRdHRtamp0a2pwMWk2b0tac2dxRTRtRXJDZjVaNGNrdVRvTjVBU0ZscGI4Zm40eDZDekhTUVR1YUZObEkzdDIrQ0NkMVlxdWhXclh3cTJ6U2VBNzBNdjlEeWpuR1RORnJwdkc5b3J1YXl3S2hVeXpTZ2p5R0lTZ3I4Z3BBcE1yUitWeEZodGVYWENZYWRpYi9BPT0tLUxzV2x2cVlmZkkxaEdueHdvM2hJcHc9PQ%3D%3D--13edda0bb821ecd76cfd4cff44554f6f99a4f54e",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "start_filling_time_oIR3qk": "1603680169",
                    "weixin_followers_subscribed": "",
                    "filled_form_scene": "form",
                    "last_fill_entry_token": "rBXDceWv",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .with_json(
                [
                    {
                        "operationName": "ShowFeature",
                        "variables": {"key": "should_use_mobile_view"},
                        "extensions": {
                            "persistedQuery": {
                                "version": 1,
                                "sha256Hash": "69bac8320cb0db576c6d775ff9cda9c9de3ffbfdab3a8010e57eda56ef10e73d",
                            }
                        },
                    }
                ]
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/graphql/f/oIR3qk")
            .post("https://jinshuju.net/graphql/f/oIR3qk")
            .with_headers(
                **{
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "*/*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-cn",
                    "origin": "https://jinshuju.net",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "referer": "https://jinshuju.net/f/oIR3qk?code=071uY61w36kabV2HO34w3xIKiw1uY619",
                    "content-length": "461",
                    "x-csrf-token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680170",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gat_gtag_UA_48208031_8": "1",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "filled_form_scene": "form",
                    "_gd_session": "RFpNV2JEVDFCeWw4TjFCOGI5TU5Zc0Jldld0NitWamFJZkgxdStYV3ZNV0hXKzVheTJ6Njg3UWlYUk9senRpc0w2aDN0TXYwRCtjUndWczF1WXFPdEhESGsxTUdjM1J5bGNHcE50RUhkVVlJSW1uT3lhLzZtNG5WUzA2WXZxazlMRlp5TDBYWU1qV0lqckhxaTJvQVBBPT0tLVI0YjlQUTBqUi9nSi82TC9kY1pjZkE9PQ%3D%3D--0c97a35f3d6848dbdc41548452a1278e8e0c48f8",
                    "csrf_token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "start_filling_time_oIR3qk": "1603680169",
                    "weixin_followers_subscribed": "",
                    "last_fill_entry_token": "rBXDceWv",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .with_json(
                [
                    {
                        "operationName": "WeixinOauthData",
                        "variables": {"code": "071uY61w36kabV2HO34w3xIKiw1uY619"},
                        "extensions": {
                            "persistedQuery": {
                                "version": 1,
                                "sha256Hash": "ec00cb7e63d2486fa1a0a0a392941ae2b6e23354fa10936b27b1544d33687fd6",
                            }
                        },
                    },
                    {
                        "operationName": "publishedDynamicAttrs",
                        "variables": {
                            "formId": "oIR3qk",
                            "code": "071uY61w36kabV2HO34w3xIKiw1uY619",
                        },
                        "extensions": {
                            "persistedQuery": {
                                "version": 1,
                                "sha256Hash": "b9e02c3e968435ec4a86b4ff7ff00d4f89ccb593df0d24aa4b71735e1c9f822d",
                            }
                        },
                    },
                ]
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/graphql/f/oIR3qk")
            .post("https://jinshuju.net/graphql/f/oIR3qk")
            .with_headers(
                **{
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "*/*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-cn",
                    "origin": "https://jinshuju.net",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "referer": "https://jinshuju.net/f/oIR3qk?code=071uY61w36kabV2HO34w3xIKiw1uY619",
                    "content-length": "937",
                    "x-csrf-token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                }
            )
            .with_cookies(
                **{
                    "filled_form_scene": "form",
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "_gd_session": "SDdpcjJ2Y0NiNjNUSWtNNFRqdVZhbjNaM1ZEM1lHd0Fha3FFa0pyY0JjVUVlM0ZiWm8zcUgvOWZiWU93b2Qzekc5eTlUN2RGOEZNUnkvK3Vnak9tR2psRjV6MFNaWW0zeG1XM3ZVSjJ2YVUzY0VIWjM3ZHZHRXF2NDFwWElJOFZwTGFheUJaV21PVDF2cE5zK0lYRzZRPT0tLStlVHBFdFk4UHBvaTdNZWQyOGZRMlE9PQ%3D%3D--f3b239ec964e536aed06ae1bd68c391dadae29a1",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680170",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gat_gtag_UA_48208031_8": "1",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "csrf_token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                    "start_filling_time_oIR3qk": "1603680169",
                    "weixin_followers_subscribed": "",
                    "last_fill_entry_token": "rBXDceWv",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .with_json(
                {
                    "operationName": "CreatePublishedFormEntry",
                    "variables": {
                        "input": {
                            "formId": "oIR3qk",
                            "entryAttributes": {"field_1": "张三"},
                            "captchaData": None,
                            "weixinAccessToken": "38_kKl0pBjXAuOsKeydfiYD5PD30G2eBP42v5EcAGIh6qc0RBZ9N7lfJwK2txFOqmMTJkPCjbLCpYTv5meDpPZ7nKVXwg67Jkf_Vk0Q1M-ydh8",
                            "xFieldWeixinOpenid": "oJGF7wcbNNCdTyObMkduNW8DwnB4",
                            "weixinInfo": {
                                "openid": "oJGF7wcbNNCdTyObMkduNW8DwnB4",
                                "nickname": "LL",
                                "sex": 1,
                                "language": "zh_CN",
                                "city": "成都",
                                "province": "四川",
                                "country": "中国",
                                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/LXqOAusU8VdpQwNRibiaczIWZVkBWIrYT5D7cs0ebxCd9racNgyJK8gNJOr6oPTflDsrzGeOUPiakIicJLlX1zSvqg/132",
                                "privilege": [],
                                "unionid": "oRZSYuF6y6oq8nXgzNmvd61ZN8Ag",
                            },
                            "prefilledParams": "",
                            "embedded": False,
                            "backgroundImage": False,
                            "formMargin": False,
                            "hasPreferential": False,
                            "fillingDuration": 6,
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "4cd6a9aef2820b2c3215f6ddfa87093869461f76f3f2016738f4307268a7df98",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/f/oIR3qk/success")
            .get("https://jinshuju.net/f/oIR3qk/success")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "accept-encoding": "gzip, deflate, br",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "accept-language": "zh-cn",
                    "referer": "https://jinshuju.net/f/oIR3qk?code=071uY61w36kabV2HO34w3xIKiw1uY619",
                }
            )
            .with_cookies(
                **{
                    "entry_token": "Oig9aOgN",
                    "formSubmitSuccess": "1",
                    "gd_ssf": "MTYwMzY4MDE3Nw%3D%3D--65cd83b2103e42857823c793ee683c25310fcc3d",
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "filled_form_scene": "form",
                    "last_fill_entry_token": "Oig9aOgN",
                    "_gd_session": "ZjhDVTRJa0U5QWxKemIxSkl5dTkvTWo5SDNwSEM3aFgrVTBxMXZxb01vb09iS0FwWFlHTTArdWpqR3NreUh2NWErVThIR3daelkrdUFVVVZ1V2Nkb0hNcExndldOcmpqcFhreEFFVlpkb3pmQ0luK01Mc0JiY3pROW5BdHRzdHozalN3aUNKQ1EwN2lEeW9FZ1BaeTZBPT0tLWdEcWVSQU9XUXgvb0VjWGRxRGdMTXc9PQ%3D%3D--21dfc1dfd83ea39abfefbef2b9785a25aa2b23a1",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680170",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gat_gtag_UA_48208031_8": "1",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "csrf_token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                    "weixin_followers_subscribed": "",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/entries/Oig9aOgN/red_envelopes/delivery.js")
            .post("https://jinshuju.net/entries/Oig9aOgN/red_envelopes/delivery.js")
            .with_headers(
                **{
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "accept": "*/*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript",
                    "x-requested-with": "XMLHttpRequest",
                    "accept-language": "zh-cn",
                    "accept-encoding": "gzip, deflate, br",
                    "origin": "https://jinshuju.net",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "referer": "https://jinshuju.net/f/oIR3qk/success",
                    "content-length": "132",
                    "x-csrf-token": "dxDRE5L9ockY/JKrMNTsiij5uTVM6NU5VEAqJV0PIwJdJwKpvpJwoKw+dtRI7tn49uhN2I+BiWjxsZeh74GyNg==",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603680178",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603267693,1603355072,1603424401,1603676817",
                    "_ga": "GA1.2.1734022612.1602570241",
                    "_gid": "GA1.2.1232973062.1603676817",
                    "_caid": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YyI%3D--a7aa5ff4679240cbedc44c969e128b535d2e0437",
                    "filled_form_scene": "form",
                    "last_fill_entry_token": "Oig9aOgN",
                    "_gd_session": "MURqa1Nwd052YWV0M1RhTGdvWU1pY255RjNlbkhLZ0VHQUk5cXQxWVYvRDdyNG1adXNpb2xISEdKSUJEc0RBMU5haG9oeVRydVRWSERPMnI4S2NsdTRRa1FMeVBVRGtsS0RlSTRFNWZ4WGR0NzVUcTBoOVdwSjFiNEtyMzE4dHcwNHZrY0JRbGttNThzUm12WHgyc0N3PT0tLU5XSnpaQ0xySFdvek5vVU5zUnQzUXc9PQ%3D%3D--b3d6db9387479a55ffbcb8e7fc02dba206dad9f2",
                    "jsj_uid": "e04b094f-4b68-42a2-a822-76798f6c9ee4",
                    "_gat_gtag_UA_48208031_8": "1",
                    "csrf_token": "Fhyv4P7922XodD+5plo+lIN7uc+D+jjV7EqxK3hpzkI8K3xa0pIKDFy228beYAvmXWpNIkCTZIRJuwyvyudfdg==",
                    "weixin_followers_subscribed": "",
                    "_gd_m_t": "eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4ZDM1YzEwYS02NTA5LTRmMGUtOWY5My1hNTlhMGEwMDljZWMifQ.ns8tMNAP0QS6PJC06N4ul3IC8S50LeLJabcHuw8lOY8",
                    "_gd_sid": "IjVmOGJiMzhlZTkzNjkyM2VhOTQ5ZTdkNSI%3D--34692b091e38bdb8d20e3ed2e3032cf6b3304c75",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                }
            )
            .with_data(
                {
                    "utf8": "✓",
                    "authenticity_token": "dxDRE5L9ockY/JKrMNTsiij5uTVM6NU5VEAqJV0PIwJdJwKpvpJwoKw+dtRI7tn49uhN2I+BiWjxsZeh74GyNg==",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/entries/Oig9aOgN/red_envelopes/delivery")
            .get("https://4vhi6a.jinshuju.co/entries/Oig9aOgN/red_envelopes/delivery")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "accept-encoding": "gzip, deflate, br",
                    "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 micromessage/7.0.17(0x17001127) NetType/WIFI Language/zh_CN",
                    "accept-language": "zh-cn",
                    "referer": "https://jinshuju.net/",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603678615",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1603449989,1603677117,1603678615",
                    "_gd_session": "WmtQczlscDAvMTI2eFEvMGF4dVBYWmVmME9Qa0d6aVl3RytwSzlQNzk2MHRHanpxRU9IOGZqK2xCVmErVVFoL29FNjliN01kbjhsOUZBdTVRcEpqeFhvL1NTMktzVHNGVTBWck80bkxBSk4vQjFzMUZpd29ocVdQRGNBcEJxRHhvVzdlZzk1SGNualdkSGdwMnd6TUpnPT0tLVREMGptRGRQcVRyaFUya241UGphc3c9PQ%3D%3D--f2d7a39617538e38e7c3e3cc27a391ea5dd5929f",
                    "referer_url": "https%3A%2F%2Fjinshuju.net%2F",
                    "jsj_uid": "9d9e991e-5beb-4330-b42c-64ab37390ad2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRedPackage().test_start()
