# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/open_form.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseOpenForm(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/f/xIksjU")
            .get("https://mo.jinshuju.net/f/xIksjU")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mo.jinshuju.net/forms/xIksjU",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                    "if-none-match": 'W/"d8fdccdfccb669bf3767acdeb7e410c0"',
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.669479930.1597286832",
                    "_smt_uid": "5f4c6fcb.35bf55f7",
                    "change_theme_btn_clicked_midautumn": "1579600505",
                    "jsj_locale": "zh-CN",
                    "_gd_sid_usd": "IjVmNzNlNjUzZTVjZGM0MjlkZDRiN2RmNyI%3D--e94c00da46872bc61395523f6815fb36551bc6be",
                    "_gd_sid_uat": "IjVmOGQ0NDQyZDQ5NmNlMmUzOGNiYjg1NSI%3D--2ec86b8a8bf92e3df9b65e80bc06f726cca44980",
                    "filled_form_scene": "form",
                    "_gid": "GA1.2.1268323698.1603244451",
                    "has_visited_dashboard_in_two_days": "true",
                    "_gd_sid_mo": "IjVmOGZlMGIxNWI2NTE2NjZkOGI0ZTQ4YyI%3D--8228f70e23423567053db53f1b2e443dbee61cf7",
                    "_jinshuju_ut": "IjVjOGI2YTBkOTYwMjY4N2U0OGI4Zjg4YSI%3D--3d0d333baebbb142e894251a445237f0e74cb611",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "start_filling_time_mxk9pC": "1603268952",
                    "_gd_sid_fusion": "IjVmOTBlODU2MGJjMmIzNjI2ZTE0ZGZiYSI%3D--dcfd5b67261ee167eca04cea0aeabbfe075b7f61",
                    "start_filling_time_kQnsXG": "1603333287",
                    "_gd_sid_staging": "IjVmOTE0MTY4NmVjNWQ5NTAxZDI1OTJiNCI%3D--10e12a95c567454d8c89a8c774bb36d3e3fc25a0",
                    "_gd_sid": "IjVmOTE2MDI0MzViNTBhMWVmNWQ4Mjc2NSI%3D--2ed8e32feee33a0ace1ae5709457ebf62f1471cb",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1602214492,1602224981,1602225263,1603435846",
                    "country_code": "CN",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "_gat_gtag_UA_48208031_14": "1",
                    "mixpanel_event_history": "open_publish_link",
                    "start_filling_time_xIksjU": "1603441230",
                    "_gat_gtag_UA_48208031_13": "1",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1603441238",
                    "csrf_token": "t5dz/iJ4eh49/pqAmnjEnepPf4JdzZ8MG5l1zkzZVJNZk98bKQr+yIVHLYOU8fcf6O4lXGgfefcc3TRkYia8Jg==",
                    "_gd_session": "OE94RmkrMk1JYm8rbzgrZXJGNzFZNGJGTlpnZTVQUjkwY0pUTXJZVnNDcHhieTBCVi9rRnpGSlpYRUpJNGhJQ1cxb3I3OGRQMFVaNWtaNVpyV1VSY1ZLWDVkUHBYcTZlTGd4amxtK255N2JmWFAvSlh5UGhjeW9leHdITlVYdWlCWVpUM2VaL3JQK3hjTzE5ZDB5ekN3PT0tLW5kSXFMbmdxRGsxRjl5dEtKQTgxZkE9PQ%3D%3D--76077b5c1d4a1bbf681babb0c7ce4dadc3553382",
                }
            )
            .extract()
            .with_jmespath("bodyfany", "a")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseOpenForm().test_start()
