# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/text_banlist_test.har
import pytest
from httprunner import HttpRunner, Config, Step, RunRequest, Parameters


class TestCaseTextBanlistTest(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "desc-form_token-form_data-assert_code-assert_message": "${read_yaml(text_normal_submit_test)}",
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)
    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/graphql/f/cBPZWA")
            .post("https://mo.jinshuju.net/graphql/f/cBPZWA")
            .with_headers(
                **{
                    "content-length": "465",
                    "accept": "*/*",
                    "x-csrf-token": "CePKAMn3aZDhj3bAIu9aRPAXKl7INA33Uy71bX6M3RcSdVp8nMeZwRtbV+aysTcb9dTUww6LSuLGpI+gzYBAPA==",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "content-type": "application/json;charset=UTF-8",
                    "origin": "https://mo.jinshuju.net",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mo.jinshuju.net/f/cBPZWA",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.669479930.1597286832",
                    "_smt_uid": "5f4c6fcb.35bf55f7",
                    "change_theme_btn_clicked_midautumn": "1579600505",
                    "show_template_for_double_zero_user": "true",
                    "first_login": "true",
                    "_gd_sid_fusion": "IjVmYWJiNzEyMGJjMmIzNTBhYzJmYTBkMyI%3D--1344321b8116367056924e9578936a3e5095348f",
                    "jsj_locale": "zh-CN",
                    "trial_just_started": "true",
                    "_gid": "GA1.2.1735364882.1606096121",
                    "has_visited_dashboard_in_two_days": "true",
                    "start_filling_time_F8zv90": "1606101391",
                    "start_filling_time_Eyq0Lj": "1606110024",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1605256477,1605752202,1605855368,1606110935",
                    "filled_form_scene": "form",
                    "_gd_sid": "IjVmYmI4MjRlNmQ4MDFkOTEwYTVhMDkzMiI%3D--4db76fd7fe46d9baf97e421dccf2cd63e0850a5f",
                    "_gd_sid_uat": "IjVmYmM2ZjAyZDQ5NmNlMDcyZjJhODZmNiI%3D--a95df1d77c8e038c0aafd5d64798cc118d002c31",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_gd_sid_mo": "IjVmYmNhMDM4NWI2NTE2MmE5NGJkMDk0ZiI%3D--a38367568f87bac697fca27c0d2874b4ae67ee86",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "start_filling_time_HG8PJn": "1606200311",
                    "start_filling_time_C0Gxbr": "1606206794",
                    "start_filling_time_ELty8i": "1606206939",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "last_fill_entry_token": "mvVIC1NJ",
                    "start_filling_time_XE0hhL": "1606213003",
                    "mixpanel_event_history": "form_updated",
                    "start_filling_time_cBPZWA": "1606214182",
                    "csrf_token": "CePKAMn3aZDhj3bAIu9aRPAXKl7INA33Uy71bX6M3RcSdVp8nMeZwRtbV+aysTcb9dTUww6LSuLGpI+gzYBAPA==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1606214181",
                    "_gat_gtag_UA_48208031_13": "1",
                    "_gd_session": "QWxsMDlZczYrdXVHMmkzSllNZEZaaysyTURHb2pib3huREI2eHhJN0QyTlJ1WHpROVZneDNwMU9KOFEvbmFObXhJZ2ludW5JY2Vld0o2aVdsajVsdUxyTUNVUmhVUGpNaWdNRnBrajd0N1kzNGw5S2kwOFh4d2VINmVVVEVNYTZCNTlmK0l5Y09lY1hCd25zYWZJSFZ3NWFWVGZQdElvOHN6STF2dDBaWXZKUXNHaGVxMi9OUGFGaFBjdFhIZ2s1a2N4bU1COGkzdzkrQm4zTFFmbGF1dWZiNEgzWVVPTzdRMU5XcnBCdHhaMFU3RFppMVQyd0xVaVgxdy9XWGFTYXhPd0s4anZ4QzY0N1N2VHVsZkJvY0gxVS94bTZsN09oTzhqeE1NQURyTGhseDJjZDRIcVBTN0hjWDRaZFBhTFFuM2hqaWR1V2tqYXBKZ0xOWGU1QUtnPT0tLUd4M2tTTm5kc0tpNnJ3V0RvTDZMWVE9PQ%3D%3D--e1f78dc4055fca99fd4c1fa03e2582d5da91fbf7",
                }
            )
            .with_json(
                {
                    "operationName": "CreatePublishedFormEntry",
                    "variables": {
                        "input": {
                            "formId": "cBPZWA",
                            "entryAttributes": {"field_1": "张三"},
                            "captchaData": None,
                            "weixinAccessToken": None,
                            "xFieldWeixinOpenid": None,
                            "weixinInfo": None,
                            "prefilledParams": "",
                            "embedded": False,
                            "backgroundImage": False,
                            "formMargin": False,
                            "hasPreferential": False,
                            "fillingDuration": 21,
                        }
                    },
                    "extensions": {
                        "persistedQuery": {
                            "version": 1,
                            "sha256Hash": "4cd6a9aef2820b2c3215f6ddfa87093869461f76f3f2016738f4307268a7df98",
                        }
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/f/cBPZWA/success")
            .get("https://mo.jinshuju.net/f/cBPZWA/success")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mo.jinshuju.net/f/cBPZWA",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{
                    "entry_token": "o3P3SMpk",
                    "gd_ssf": "MTYwNjIxNDIwNQ%3D%3D--4105c7d2e1d3e7a331f4680d5aa199a6b4fe9bf5",
                    "formSubmitSuccess": "1",
                    "_ga": "GA1.2.669479930.1597286832",
                    "_smt_uid": "5f4c6fcb.35bf55f7",
                    "change_theme_btn_clicked_midautumn": "1579600505",
                    "show_template_for_double_zero_user": "true",
                    "first_login": "true",
                    "_gd_sid_fusion": "IjVmYWJiNzEyMGJjMmIzNTBhYzJmYTBkMyI%3D--1344321b8116367056924e9578936a3e5095348f",
                    "jsj_locale": "zh-CN",
                    "trial_just_started": "true",
                    "_gid": "GA1.2.1735364882.1606096121",
                    "has_visited_dashboard_in_two_days": "true",
                    "start_filling_time_F8zv90": "1606101391",
                    "start_filling_time_Eyq0Lj": "1606110024",
                    "Hm_lvt_47cd03e974df6869353431fe4f4d6b2f": "1605256477,1605752202,1605855368,1606110935",
                    "filled_form_scene": "form",
                    "_gd_sid": "IjVmYmI4MjRlNmQ4MDFkOTEwYTVhMDkzMiI%3D--4db76fd7fe46d9baf97e421dccf2cd63e0850a5f",
                    "_gd_sid_uat": "IjVmYmM2ZjAyZDQ5NmNlMDcyZjJhODZmNiI%3D--a95df1d77c8e038c0aafd5d64798cc118d002c31",
                    "_jinshuju_ut": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3MiI%3D--8f535c3330099d30d8078fe3be96ec08f00eb321",
                    "_gd_sid_mo": "IjVmYmNhMDM4NWI2NTE2MmE5NGJkMDk0ZiI%3D--a38367568f87bac697fca27c0d2874b4ae67ee86",
                    "jsj_uid": "ec5ce3b2-5149-4620-b475-e2a633d5dccf",
                    "country_code": "CN",
                    "start_filling_time_HG8PJn": "1606200311",
                    "start_filling_time_C0Gxbr": "1606206794",
                    "start_filling_time_ELty8i": "1606206939",
                    "_caid": "IjVkZDYyNjU0NjZhYjMzNDZhNzI5MjA3NCI%3D--d141bd1f24ec3955b11ea186700716f2a6e71db6",
                    "start_filling_time_XE0hhL": "1606213003",
                    "mixpanel_event_history": "form_updated",
                    "csrf_token": "CePKAMn3aZDhj3bAIu9aRPAXKl7INA33Uy71bX6M3RcSdVp8nMeZwRtbV+aysTcb9dTUww6LSuLGpI+gzYBAPA==",
                    "Hm_lpvt_47cd03e974df6869353431fe4f4d6b2f": "1606214181",
                    "_gat_gtag_UA_48208031_13": "1",
                    "last_fill_entry_token": "o3P3SMpk",
                    "_gd_session": "VkVaLzVZQWdoRWRoVDFnSmRld29PbTVvdW1CaFlJUXU0L2p3UnhqU0VoNDRNSTJXU0FrcmNqR1RwTUo3cW9LRjVYRVRRYUxyZlp4MjNhMFZyOXA1Z2tHdnpCazRvdWlRbzRvSlU3YkpNNUcxVm1LalJ1VnF2S0dkVmFGMURXTGRQZWRvV21abk9Bb3VhU1VpU2Vvd05peTFxYWtpNGxPVFdaNE1CRE5jUUtoZEYrZzgwUWdjK3hDVHN1N1N4RkI0VzBlVkRnVGQ2WElhVmZNYlEzNVd3WDZhdXJ0N3c2TXRFUDlLTFFad2ZybTJ2QXRhcldNWklNcVo0MTlacFZ1YTNvQ0pUQ0E5VGdXaXAwQlI0TUJtdmU5eTRtR1JhYUdtcjZzMXBPMHpEM0c1cXg0T1ZtSnZValFGemVzM29rTHR0ckUrRHJrUlJjaWVNcElDR2FVOEJ3PT0tLU5BbTFTVTN3bC80c2ZtWW0vRXJXMlE9PQ%3D%3D--5785d4c1046b45ef2513f1364c86391493e8bb14",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseTextBanlistTest().test_start()
